# Generated by Django 4.1.5 on 2023-01-23 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies_app', '0003_alter_movie_pic_uri'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='pic_uri',
        ),
        migrations.AddField(
            model_name='movie',
            name='pic_url',
            field=models.URLField(db_column='pic_url', max_length=512, null=True),
        ),
    ]
