# Generated by Django 4.1.5 on 2023-01-23 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies_app', '0004_remove_movie_pic_uri_movie_pic_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='rating_date',
            field=models.DateField(db_column='date', default='1900-01-01'),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField(db_column='review')),
                ('review_date', models.DateField(db_column='date', default='1900-01-01')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='movies_app.movie')),
            ],
            options={
                'db_table': 'reviews',
            },
        ),
    ]
