# Generated by Django 4.1.5 on 2023-01-29 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies_app', '0006_movie_release_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='name', max_length=256)),
                ('roll', models.TextField(db_column='roll')),
                ('salary', models.IntegerField(db_column='salary')),
                ('movies', models.TextField(db_column='movies')),
                ('birth_year', models.IntegerField(db_column='birth_year')),
            ],
            options={
                'db_table': 'Actors',
            },
        ),
        migrations.CreateModel(
            name='Movie_Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary', models.IntegerField()),
                ('main_role', models.BooleanField()),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies_app.actor')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies_app.movie')),
            ],
            options={
                'db_table': 'movie_actors',
            },
        ),
        migrations.AddField(
            model_name='movie',
            name='actor',
            field=models.ManyToManyField(through='movies_app.Movie_Actor', to='movies_app.actor'),
        ),
    ]
