# Generated by Django 4.1.5 on 2023-01-29 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies_app', '0007_actor_movie_actor_movie_actor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='actor',
            new_name='actors',
        ),
        migrations.RemoveField(
            model_name='actor',
            name='roll',
        ),
        migrations.RemoveField(
            model_name='actor',
            name='salary',
        ),
        migrations.AddField(
            model_name='movie_actor',
            name='roll',
            field=models.TextField(db_column='roll', default='none'),
            preserve_default=False,
        ),
    ]
