# Generated by Django 4.1.5 on 2023-01-29 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies_app', '0009_alter_movie_actor_main_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie_actor',
            name='salary',
            field=models.IntegerField(blank=0, null=True),
        ),
    ]
