# Generated by Django 4.1.5 on 2023-01-29 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies_app', '0010_alter_movie_actor_salary'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='actor',
            table='actors',
        ),
    ]
