# Generated by Django 4.1.5 on 2023-01-29 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies_app', '0011_alter_actor_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actor',
            name='movies',
        ),
    ]
